language: C
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
fail_fast: true
script:
- cd cdep
- ./cdep fullfill .. ${TRAVIS_TAG:-0.0.0} $(ls cdep-manifest*.yml)
- ./cdep
- ./cmakeify -wf .cdep/examples/cmake  --group-id com.github.jomof --artifact-id stb-examples --target-version 0.0.0
- ./wget https://com.github.jomof/jomof/tools
- printenv
#- bin/linux/amd64/github-release upload --user $user --repo $repo --tag $tag --name $name --file $file
