language: C
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
fail_fast: true
script:
- cd cdep
- ./cdep fullfill .. ${TRAVIS_TAG:-0.0.0} $(ls cdep-manifest*.yml) | tee metafist.txt
- ./cdep
#- ./cmakeify -wf .cdep/examples/cmake  --group-id com.github.jomof --artifact-id stb-examples --target-version 0.0.0
- git clone https://com.github/jomof/tools
- cat metafist | tools/github_release_folder jomof stb ${TRAVIS_TAG:-none}
